name: flutter_map_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.9
  flutter_dotenv: ^5.2.1
  flutter_map: ^7.0.0
  http: ^1.4.0
  latlong2: ^0.9.1
  geolocator: ^14.0.1
  flutter_map_marker_cluster: ^1.4.0
  flutter_map_animations: ^0.7.1
  flutter_cache_manager: ^3.4.1
  random_avatar: ^0.0.8
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.3
  loading_indicator: ^3.1.1
  provider: ^6.0.5
  flutter_launcher_icons: ^0.14.4
  toastification: ^3.0.3


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/marker.png
    - assets/marker_active.png
    - assets/logo_transparent.png
    - assets/phone.png
